version: "3.9"

services:
  redis:
    image: redis:7

  api:
    build: ./api
    env_file:
      - .env         # OPTION_SYMBOLS, POLL_SEC, RISK_FREE
    ports:
      - "8000:8000"
    depends_on:
      - redis
